<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S4-EditNote</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>40c4af1f-4ef7-4d20-b1ec-59eaf0797c82</testSuiteGuid>
   <testCaseLink>
      <guid>04ef2576-beb3-4a8c-95c5-fcf1da56a1fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S4-EditNote/S4-TC1-Edit the text note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f448e487-6b83-4f38-8dbf-95bcf6c4fba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da04383b-aa36-42b5-89f9-b13a971497a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30f31832-242b-41a0-aaf2-84aa2be49470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S4-EditNote/S4-TC2-Edit the checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13cd734a-bfac-41a4-a544-4f9e4dbb6355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcf60e55-c821-4acc-9d72-5f1c06d7e8e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe43b59-ebcf-41d1-baee-f452da8c0529</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>371b050b-e958-497a-a051-63f0e39ca6ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S4-EditNote/S4-TC3-Revert the note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5581fe9c-8db7-4e4f-938c-6eb1a00454b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f23144eb-884c-45b4-9ced-ee1443c5366f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
