<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S6-AchieveNoteSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9d1245af-aaac-4b59-8224-549dae573e47</testSuiteGuid>
   <testCaseLink>
      <guid>f7d9d93f-3798-452a-b17c-b35fe34cc78f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S6-AchieveNote/S6-TC1-Successfully achieve a text note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>226112f1-0d27-4365-b8b9-9a22bacda3f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59417e5f-cb22-49e7-9b0a-3ffc95b4505e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S6-AchieveNote/S6-TC2-Successfully achieve a checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11c082f6-39a5-459c-8786-d9ae5a60f909</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
